hash-format = "sha256"

[[files]]
file = "mods/estherserver.pw.toml"
hash = "93f2ee4d82ef18453ae7e0979401550611e0ec1ab6f2c08731c14aa841983f67"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "0033c5a00c46d5d7b6cf77b19fa76ce5c78a613f3128dcadb3588fa5841ae489"
metafile = true
