hash-format = "sha256"

[[files]]
file = "mods/estherserver.pw.toml"
hash = "c1152e1153585b755bb3be6811e3607a603dc29103b088a091ad2bf627ea0f2f"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "0033c5a00c46d5d7b6cf77b19fa76ce5c78a613f3128dcadb3588fa5841ae489"
metafile = true
