hash-format = "sha256"

[[files]]
file = "mods/estherserver.pw.toml"
hash = "bd71f3aeda13046d3eb247e4d62f9a1548b1d6b58b1247f91979fddf6d268acd"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "0033c5a00c46d5d7b6cf77b19fa76ce5c78a613f3128dcadb3588fa5841ae489"
metafile = true
