hash-format = "sha256"

[[files]]
file = "mods/estherserver.pw.toml"
hash = "a2aa95551b83a726eabb7c641de697f407b39c1c56a6ea224c6774532e600b55"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "0033c5a00c46d5d7b6cf77b19fa76ce5c78a613f3128dcadb3588fa5841ae489"
metafile = true
