hash-format = "sha256"

[[files]]
file = "mods/estherserver.pw.toml"
hash = "f7adfbbadc0aef56ae3e2a8d12d12b3e7c3c87362cd874240e5aae76108012a7"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "0033c5a00c46d5d7b6cf77b19fa76ce5c78a613f3128dcadb3588fa5841ae489"
metafile = true
