hash-format = "sha256"

[[files]]
file = "mods/estherserver.pw.toml"
hash = "ac1e8da9e1e23f5ea1ff1879832897c5eec2386abd572802561e5ca1a5f58479"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "0033c5a00c46d5d7b6cf77b19fa76ce5c78a613f3128dcadb3588fa5841ae489"
metafile = true
