hash-format = "sha256"

[[files]]
file = "mods/estherserver.pw.toml"
hash = "eb2eb98e629570326b4dabb1eb931cac7b736576e39a987c5c34097621701a5e"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "0033c5a00c46d5d7b6cf77b19fa76ce5c78a613f3128dcadb3588fa5841ae489"
metafile = true
