hash-format = "sha256"

[[files]]
file = "mods/estherserver.pw.toml"
hash = "6effe83b60521657e80cf9155a1b10273728ad6bdc1fb47fcedd223722dd631d"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "0033c5a00c46d5d7b6cf77b19fa76ce5c78a613f3128dcadb3588fa5841ae489"
metafile = true
