hash-format = "sha256"

[[files]]
file = "mods/estherserver.pw.toml"
hash = "a09843370bc79d66168207cae742ce7d642fe33b6cd2260cf267b16bdb06136d"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "0033c5a00c46d5d7b6cf77b19fa76ce5c78a613f3128dcadb3588fa5841ae489"
metafile = true
