name = "Esther Server"
author = "juyoung"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c16c3efc6ac5cb5a68f82032b32a0e7d617b2367bfc5f37c8fe21d5827ff5a3b"

[versions]
minecraft = "1.21.4"
neoforge = "21.4.156"
