name = "Esther Server"
author = "juyoung"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50ac67f1a3787dec5e2cdc61f2963cb297e23cd4873a492750d1b7ae4ddcfd0b"

[versions]
minecraft = "1.21.4"
neoforge = "21.4.156"
