name = "Esther Server"
author = "juyoung"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76325d6dcce9f4bd4c380a7efcea3636d659bb619da4e81f91707e3e9a5575f5"

[versions]
minecraft = "1.21.4"
neoforge = "21.4.156"
