name = "Esther Server"
author = "juyoung"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "100eb58594aa25a75cf51a223eb5d57a1553605dfa60959bddfb8745902f85c1"

[versions]
minecraft = "1.21.4"
neoforge = "21.4.156"
