name = "Esther Server"
author = "juyoung"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7bfe62587c64e2103bc912f79b3b793a9b79d383efe690c2882d828390bd8c53"

[versions]
minecraft = "1.21.4"
neoforge = "21.4.156"
