name = "Esther Server"
author = "juyoung"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "813a7f3ab425fb65c687c58f94f74042e5458f88d3cc522eef79d0f2e1baecdf"

[versions]
minecraft = "1.21.4"
neoforge = "21.4.156"
